server:
  port: 8888
  error:
    include-message: always

logging:
  file:
    name: /logs/${spring.application.name}.log

management:
  security:
    enabled: true
  endpoints:
    health:
      sensitive: false
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      post:
        enabled: true
    health:
      show-details: when-authorized

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          refresh-rate: 10000
          uri: https://github.com/Pawel-Radel/radel-core-environment-configuration
          username: pawel-radello@wp.pl
          password: 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
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/test/protocol/openid-connect/certs
  config:
    activate:
      on-profile: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://${admin.user.name}:${admin.user.password}@localhost:8761/eureka/

admin:
  user:
    name: pawel
    password: radel
